// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbpdczuksmxfvuerdbrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndicGRjenVrc214ZnZ1ZXJkYnJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc3NjIxNTQsImV4cCI6MjA5MzMzODE1NH0.eiGgzSer6ITVxdIVL_MCI1i31uYGtE-2P8Am_JD34nY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});